server {
    listen 80;
    root /usr/share/nginx/html;
    
    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Desactivar logs innecesarios
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    # Caché para recursos estáticos
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
}
